- README.md
- bin/clusternatorCli-es5.js
- bin/clusternatorCli.js
- docs/setup.md
- lib/cli.js
- lib/clusternator.js
- lib/ec2Manager.js
- src/cli.js
- src/clusternator.js
- src/ec2Manager.js
- src/taskDefinitionManager.js
- src/taskServiceManager.js
> Create docs directory

- .gitignore
- docs/stories.md
- gulpfile.js
- lib/clusternator.js
- lib/taskDefinitionManager.js
- lib/taskServiceManager.js
- package.json
- spec/chai.js
- spec/util.spec.js
`gulp transpile` will transpile src->lib
`gulp` defaults to `transpile`
`gulp watch` will watch `src/**/*.js` and run transpile on changes
> Adds gulp, gulp tasks from manual transpilation, and a watch task

- Dockerfile
- bin/clusternatorCli-es5.js
- clusternator-server-definition.json
- examples/elb-tutorial/README.md
- examples/elb-tutorial/appdef.json
- lib/aws/clusterManager.js
- lib/aws/ec2FullConfig.js
- lib/aws/ec2Manager.js
- lib/aws/networkAclManager.js
- lib/aws/securityGroupManager.js
- lib/aws/subnetManager.js
- lib/aws/taskServiceManager.js
- lib/aws/vpcManager.js
- lib/cli.js
- lib/clusternator.js
- lib/config.js
- lib/constants.js
- lib/environment.js
- lib/resourceIdentifier.js
- lib/server/main.js
- lib/server/pullRequest.js
- lib/util.js
- package.json
- src/cli.js
- src/resourceIdentifier.js
- src/server/main.js
- src/server/pullRequest.js
> Server setup w/ Docker

- .npmignore
- package.json
- src/constants.js
https://aws.amazon.com/amazon-linux-ami/faqs/#lock
> Updates default ECS AMI to address some issues with AWS updates

- package.json
- src/api/0.1/cli/cli-api.js
- src/api/0.1/cli/project.js
- src/api/0.1/project-fs/fs.js
- src/api/0.1/project-fs/git-hooks.js
- src/api/0.1/project-fs/private.js
- src/skeletons/git-post-commit
- src/skeletons/git-pre-commit
- `clusternator init` installs hooks if user says 'Y' to question
- `clusternator git-hook-install` installs hooks manually, and non-destructively
- `clusternator git-hook-remove` removes git hooks cleanly
> Git hooks can now be automatically installed during `init`

- src/api/0.1/cli/cli-api.js
- src/api/0.1/cli/deployments.js
- src/api/0.1/js/js-api.js
- src/aws/deploymentManager.js
- src/aws/ec2Manager.js
- src/aws/projectManager.js
- src/aws/securityGroupManager.js
Update feature is pending, just wanted to ship this by itself for now.
> Remove sha from create/destroy deployment

- src/api/0.1/project-fs/git-hooks.js
- src/api/0.1/project-fs/skeletons/git-post-commit
- src/api/0.1/project-fs/skeletons/git-post-merge
- src/api/0.1/project-fs/skeletons/git-pre-commit
This addressed #274 directly and also partially addresses #269 
Additionally #266 should be cleared up.
> Fix shebangs in templates and on empty files (#274)

- docs/_config.yml
- docs/pages/guide/admin/authentication.md
- docs/pages/guide/installation.md
> Fixes doc typo and highlighting type (#257 and #258)

- src/aws/ec2/ec2-filter.js
- src/aws/ec2/ec2-filter.spec.js
- src/aws/ec2/security-groups.js
This should fix security group errors that occur when ec2 tagging fails
> Security group search by name

- src/util.js
- src/util.spec.js
I made this a PR all by itself because I think we'll end up with a PR for each service that starts using this and it would be nice to be able to work on those PR's in parallel.  
Also it would be nice to not use `Q` but that's a whole other chore.
The way the retryFunction is currently setup it's arguments look like:  `function makeRetryPromise(promiseReturningFunction, retryCount, delay, multiplier, failOn, label)`
- If given a promise returning function and no other arguments the function will call the promise and resolve/reject as "normal"
- If given a promise returning function and a retry count it will retry that many times before failing
- If given a promise returning function, a retry count, and delay, it will delay the retry
- If given a promise returning function, a retry count, …
> Adds a function that retries promises under certain circumstances

- src/api/0.1/cli/deployments.js
- src/api/0.1/js/js-api.js
- src/api/0.1/rest/rest-api.js
- src/aws/projectManager.js
- src/clusternator/deployments.js
- src/clusternator/projectManager.js
> Deploy server hookup

- docs/pages/guide/quick-start.md
> Beefed up the quickstart documentation page

- docs/pages/guide/developing-and-contributions.md
> Added a blurb about error handling to the contrib guidelines.

- .clusternator/config.json
- src/api/0.1/cli/cli-api.js
- src/api/0.1/cli/project-db.js
- src/api/0.1/js/js-api.js
- src/api/0.1/rest/rest-api.js
- src/clusternator/project-data.js
- src/util.js
- src/util.spec.js
> Change project's Slack channel

- src/api/0.1/project-fs/skeletons/docker-build.js
> Fixes (#343) SSH public key uploads

- package.json
> chore(package): update eslint to version 2.7.0

- package.json
> chore(package): update gulp-istanbul to version 0.10.4

- package.json
> chore(package): update aws-sdk to version 2.3.1

- package.json
> chore(package): update yargs to version 4.4.0

- src/api/0.1/cli/cli-api.js
> Remove 'describe-services' from CLI.

- .clusternator/docker-build.js
- circle.yml
> Self deploy

- package.json
> chore(package): update inquirer to version 1.0.0

- package.json
> chore(package): update eslint to version 2.8.0

- package.json
- src/util.js
@rafkhan can you give this a look please
> Fixes a critical bug that stops CLI "wizards" from running

- package.json
> chore(package): update nodemon to version 1.9.2

- package.json
> chore(package): update superagent to version 1.8.3

- package.json
> chore(package): update sinon to version 1.17.4

- package.json
@rafkhan can you please give this a check?  I would recommend actually doing a local build an validating that yargs works as expected.
> Dep update yargs

- package.json
> chore(package): update aws-sdk to version 2.3.9

- package.json
> chore(package): update body-parser to version 1.15.1

- package.json
> chore(package): update concurrently to version 2.1.0

- package.json
- src/server/clusternator-api/api-0.1.js
- src/server/main.js
@bennett000 
@SethDavenport when this issue is resolved (and tested), the runtime should be good to go.
> DO NOT MERGE. Passport fix.
